name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Show GitHub context variables
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (with dev)
        run: poetry install --with dev --no-interaction

      - name: Run linting and checks (if Makefile exists)
        run: |
          if [ -f Makefile ] && grep -q '^check:' Makefile; then
            make check
          else
            echo "No Makefile or check target, skipping linting."
          fi

      - name: Run tests
        run: poetry run pytest
